!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers:
- mHandle: 253
  mName: I2C NavX X Accel
  mType: com.snobot.simulator.module_wrapper.BaseAccelerometerWrapper
- mHandle: 254
  mName: I2C NavX Y Accel
  mType: com.snobot.simulator.module_wrapper.BaseAccelerometerWrapper
- mHandle: 255
  mName: I2C NavX Z Accel
  mType: com.snobot.simulator.module_wrapper.BaseAccelerometerWrapper
mAnalogIn:
- mHandle: 0
  mName: Analog In 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiAnalogInWrapper
mAnalogOut: []
mDefaultI2CWrappers:
  1: NavX
mDefaultSpiWrappers:
  0: ADXRS450
mDigitalIO:
- mHandle: 0
  mName: Digital IO 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
- mHandle: 1
  mName: Digital IO 1
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
- mHandle: 2
  mName: Digital IO 2
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
- mHandle: 3
  mName: Digital IO 3
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
mEncoders:
- mConnectedSpeedControllerHandle: -1
  mHandle: 0
  mName: Encoder 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiEncoderWrapper
- mConnectedSpeedControllerHandle: -1
  mHandle: 1
  mName: Encoder 1
  mType: com.snobot.simulator.module_wrapper.wpi.WpiEncoderWrapper
mGyros:
- mHandle: 0
  mName: Analog Gyro
  mType: com.snobot.simulator.module_wrapper.wpi.WpiAnalogGyroWrapper
- mHandle: 100
  mName: ADXRS450 Gyro
  mType: com.snobot.simulator.simulator_components.adx_family.ADXRS450GyroWrapper
- mHandle: 253
  mName: I2C NavX Yaw
  mType: com.snobot.simulator.module_wrapper.BaseGyroWrapper
- mHandle: 254
  mName: I2C NavX Pitch
  mType: com.snobot.simulator.module_wrapper.BaseGyroWrapper
- mHandle: 255
  mName: I2C NavX Roll
  mType: com.snobot.simulator.module_wrapper.BaseGyroWrapper
mPwm:
- mHandle: 0
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 1
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 1
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
mRelays: []
mSimulatorComponents: []
mSolenoids:
- mHandle: 0
  mName: Solenoid 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
